import json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
rig=json.loads((root/'ios/Packages/SkinstelMascot/Sources/SkinstelMascot/Resources/MascotRig.json').read_text())
svg=''.join('<path id="'+p['name']+'" d="'+' '.join(c['op']+' '+' '.join(str(x) for x in c['values']) for c in p['commands'])+'" fill="'+(p['fill'] or 'none')+'" stroke="'+(p['stroke'] or 'none')+'" stroke-width="'+str(p['width'])+'" stroke-linejoin="round" stroke-linecap="round"/>' for p in rig)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Skinstel • animated companion</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4ede0;color:#482631;font:16px system-ui,sans-serif}main{max-width:860px;margin:auto;padding:40px 24px}small{letter-spacing:.2em}h1{font:clamp(32px,6vw,52px) Georgia;margin:16px 0}p{color:#756862;line-height:1.6}.stage{position:relative;height:390px;border-radius:28px;background:#fffaf3;overflow:hidden;border:1px solid #e7dace;margin:28px 0}svg{position:absolute;width:270px;height:338px;top:24px;left:calc(50% - 135px)}.controls{display:flex;gap:8px;flex-wrap:wrap}button{border:1px solid #d6b6a8;border-radius:30px;padding:12px 18px;background:#fffaf3;color:#482631;font:inherit;cursor:pointer}button[aria-pressed=true],button#play{background:#a35848;color:white}label{display:block;margin:20px 0}input{accent-color:#a35848}footer{font-size:13px;color:#756862;border-top:1px solid #ddcabc;padding-top:20px}.note{font-size:14px}</style>
<main><small>SKINSTEL / MOTION PLAYGROUND</small><h1>A little companion.<br>Made to move.</h1><p>Choose an action. The legs, arm, face and body animate separately in code.</p><div class="stage" id="stage"><svg id="character" viewBox="0 0 320 400" aria-hidden="true"><ellipse cx="165" cy="380" rx="69" ry="6.5" fill="#000" opacity=".08"/><g id="bodyRig">__SVG__<path id="scanLine" d="M57 246H117" stroke="#A35848" stroke-width="3" style="display:none"/><g id="sparkles" fill="none" stroke="#BB8B3D" stroke-width="2"></g></g></svg></div><div class="controls" id="actions"></div><label><input type="checkbox" id="travel" checked> Walk across the screen</label><div class="controls"><button id="play">Pause</button></div><p class="note" id="status" role="status">Walking • animation runs locally, without a network request.</p><footer>Code-drawn adaptation of your mascot. SwiftUI package included. Reduced Motion is respected. This preview shares the vector artwork and motion formulas with the native component; it is not an iOS simulator.</footer></main>
<script>
const rig=__RIG__,names=['idle','walk','wave','scan','celebrate'],$=id=>document.getElementById(id);let action='walk',playing=true,t=0,last=null;const reduce=matchMedia('(prefers-reduced-motion: reduce)');
for(const name of names){const b=document.createElement('button');b.textContent=name[0].toUpperCase()+name.slice(1);b.dataset.action=name;b.setAttribute('aria-pressed',name===action);b.onclick=()=>{action=name;t=0;document.querySelectorAll('[data-action]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.action===action));$('status').textContent=name[0].toUpperCase()+name.slice(1)+' • animation runs locally, without a network request.';draw()};$('actions').append(b)}
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play'};$('travel').onchange=draw;reduce.addEventListener('change',draw);document.addEventListener('visibilitychange',()=>last=null);
function draw(){const animate=!reduce.matches,time=animate?t:0,step=Math.sin(time*2*Math.PI/.8);let bob=0,lean=0,arm=0,breath=1,left=0,right=0,eye=1;const blink=time%4.2;if(animate){if(blink>3.95)eye=Math.max(.08,Math.abs(blink-4.075)/.125);switch(action){case'idle':breath=1+Math.sin(time*2)*.012;break;case'walk':left=step*24;right=-left;bob=-Math.abs(step)*5;lean=step*1.2;break;case'wave':arm=110+Math.sin(time*7)*14;breath=1+Math.sin(time*2)*.008;break;case'scan':lean=Math.sin(time*2)*2;breath=1+Math.sin(time*2)*.008;break;case'celebrate':bob=-Math.abs(Math.sin(time*4))*15;arm=100+Math.sin(time*6)*10;left=-Math.sin(time*4)*8;right=-left;break}}
const width=Math.min(270,$('stage').clientWidth),span=Math.max(0,$('stage').clientWidth-width),moving=animate&&action==='walk'&&$('travel').checked&&span>0,distance=time*70*(width/320),phase=moving?distance%(span*2):0,back=moving&&phase>span,x=moving?(back?span*2-phase:phase):span/2;$('character').style.left=x+'px';$('character').style.width=width+'px';$('character').style.transform=back?'scaleX(-1)':'';
$('bodyRig').setAttribute('transform',`translate(160 ${332+bob}) rotate(${lean}) scale(1 ${breath}) translate(-160 -332)`);
for(const p of rig){let tr='';if(p.name==='leftLeg')tr=`rotate(${left})`;if(p.name==='rightLeg')tr=`rotate(${right})`;if(p.name==='rightArm')tr=`rotate(${arm})`;if(p.name==='leftEye'||p.name==='rightEye')tr=`scale(1 ${eye})`;$(p.name).setAttribute('transform',`translate(${p.pivot}) ${tr} translate(${-p.pivot[0]} ${-p.pivot[1]})`)}
$('scanLine').style.display=action==='scan'?'':'none';$('scanLine').setAttribute('transform',`translate(0 ${animate?Math.sin(time*3)*20:0})`);$('sparkles').innerHTML=action==='celebrate'?Array.from({length:5},(_,i)=>{const a=i*Math.PI/4+Math.PI,r=animate?112+Math.sin(time*4+i)*9:112,x=166+Math.cos(a)*r,y=165+Math.sin(a)*r;return `<path d="M${x-4} ${y}h8 M${x} ${y-4}v8"/>`}).join(''):'';
}
function frame(now){if(last!==null&&playing&&!document.hidden&&!reduce.matches)t+=(now-last)/1000;last=now;draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
</script></html>'''.replace('__SVG__',svg).replace('__RIG__',json.dumps(rig))
(root/'designs/mascot-animation/preview.html').write_text(html)
